### ISSUE TITLE
Test out Cosmos Simply VC Panic

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#126]
There's a new version of SimplyVC panic. 

We should set up a parallel instance of panic without disrupting our current panic that we're using for pager duty in production.

The purpose here is to simply evaluate whether it's worth migrating to the new version. Once we have it running, let's discuss on our next internal testnet call

https://github.com/SimplyVC/panic/releases/tag/v1.1.0

**Comment by dasanchez** [comment]
Short version of the feedback is: alerting tools are great, dashboard is a bit clunky and doesn’t feel like such a great value add as compared to grafana / prometheus configuration that many validators use. Some more details:

- I like that it’s easy to get alerts into many different services (e.g., telegram, slack, pagerduty)
- The types of alerts that are supported have expanded quite a bit to not just include the usual (missed blocks, missing peers, unreachable node) to also other network alerts (governance proposals, GitHub releases, docker registry tags). The value add here is that you can use a single Telegram channel for all alerts
- For validators who validate across many networks, it’s probably nice that it’s compatible with other networks (supports substrate and chainlink nodes). Not immediately useful to us, but would be curious to know if larger validators find it useful (perhaps not because many larger validators create their own tooling around monitoring/alerting)
- Probably the biggest improvement is the fine grained control you have over all the alert levels in each category. This is almost necessary to maintain signal-noise given the number of alerts they now support
- Anecdotally, this new version of PANIC seems slightly more sensitive than the previous one when it comes to alerting on reachability of our nodes (maybe a good thing? but it’s been bit noisier)
- They have built a nice web based UI to configure the alert levels. However, I think this might be an issue for us given we are trying to automate a lot of our deployments. I’d rather work with a config file than a web wizard so we can version control and port over our configurations. We couldn’t easily figure out how to do that.
- They have added a dashboard for monitoring, which is okay, but personally I’d just use our prometheus / grafana (which is more customizable and easier to configure and deploy)
