### ISSUE TITLE
Grafana / Prometheus monitoring

### ISSUE THREAD

**Issue by ASoTNetworks** [hyphacoop/cosmos-organizing#33]

**Comment by uditvira** [comment]
- el is proposing to get a Digital Ocean vm to run prometheus/grafana offsite so that we aren't running our monitoring stack directly on the stack that we're monitoring
- [ ] create matrix channel to dump alerts from prometheus/grafana running on DO
- [ ] el/bae/uv to have a conversation about long term monitoring solution

**Comment by uditvira** [comment]
- [ ] move to Cosmos project on digital ocean and ensure access to all Cosmos team members
- [ ] monitor three additional nodes, currently running under the vega-testnet project on Digital Ocean
  - [ ] full-node-02, TOR1 / 8GB / 160GB Disk, 165.22.235.50
  - [ ] full-node-01, TOR1 / 8GB / 160GB Disk, 134.122.35.247
  - [ ] state-sync-test-01, TOR1 / 8GB / 160GB Disk, 143.198.41.219
 - [ ] update the board configuration so that it's more helpful. currently the boards and graph names are hard to interpret. which node is which? which graph should I be looking at for disk usage? this is not clear.

**Comment by ASoTNetworks** [comment]
What are the credentials for logging into those DO VMs to setup the node-exporter?

**Comment by uditvira** [comment]
access given

**Comment by ASoTNetworks** [comment]
I am working on a ansible playbook to install and configure node_exporter

**Comment by uditvira** [comment]
elon will place ansible in the scripts dir (to be done today)

**Comment by ASoTNetworks** [comment]
Opened PR https://github.com/hyphacoop/cosmos-organizing/pull/51

I want to also make a role or playbook to automatically add to Prometheus.

**Comment by ASoTNetworks** [comment]
I have added the above playbook with an interactive wrapper script for ease of use.

**Comment by uditvira** [comment]
Let's close this issue for now and we can talk about how to move this forward with Mauve's work on Thursday at 10:30 next week
