### ISSUE TITLE
Reproduce validate genesis issue by validating an exported genesis from mainnet

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#80]

**Comment by ASoTNetworks** [comment]
I synced a mainnet node and export the genesis  at height 9961097 with the command `~/.gaiad/cosmovisor/current/bin/gaiad --home /home/gaia/.gaiad export --for-zero-height --height=9961097 &> mainnet-genesis.json`

`gaiad` wrote to stderr instead of stdout so I had to remove first few lines due to the status messages when it is exporting.

Verifying resulted in the same error as the testnet `genesis.json` file
`$ ~/.gaiad/cosmovisor/current/bin/gaiad validate-genesis mainnet-genesis.json --log_level debug`
```
Error: error validating genesis file mainnet-genesis.json: name field cannot be blank
Usage:
  gaiad validate-genesis [file] [flags]

Flags:
  -h, --help   help for validate-genesis

Global Flags:
      --home string         directory for config and data (default "/home/gaia/.gaia")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
```

**Comment by uditvira** [comment]
@ASoTNetworks can you confirm gaia version you were using?

**Comment by ASoTNetworks** [comment]
I was using v6.0.4 for mainnet.

**Comment by uditvira** [comment]
This one is being tracked in gaia repo. closing here
