### ISSUE TITLE
Templates for proposal types (incl 'delete me' notes for OP)

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-organizing#89]

**Comment by LexaMichaelides** [comment]
- [ ] 'Delete me' notes
- [ ] Community Spend
- [ ] Param Change
- [ ] Signaling
- [ ] Software Upgrade

Note that Software Upgrade template is part of our Q2 deliverable (Soft-governance around the proposal for the software upgrade).

Should also be aware that we will likely need to revisit when Rho becomes active since proposal types will change.

**Comment by dasanchez** [comment]
@LexaMichaelides this might help re: Software Upgrade
https://github.com/hyphacoop/cosmos-configurations-private/wiki/Billy's-Proposal-Formatting-Guide
